Add logging
Pet-projects-CodePET/Backend pull request #139
Opened 2024-03-22 20:15 UTC by Denis-Shtanskiy

Добавил логирование

2024-03-24 06:06 UTC, ArtemKAF requested changes
Не лучшее решение и есть что исправить.

2024-03-24 06:06 UTC, ArtemKAF commented on src/backend/config/settings/base.py
> +LOGGING_MODULE = getenv("DJANGO_SETTINGS_MODULE", "config.settings.prod")
https://github.com/Pet-projects-CodePET/Backend/blob/77fd62ce631c71fd0db3bff22d5c5de2c9b1ef99/src/backend/config/settings/base.py#L204-L204
Это лишнее.

2024-03-24 06:06 UTC, ArtemKAF commented on src/backend/config/settings/base.py
> +        "file": {
https://github.com/Pet-projects-CodePET/Backend/blob/77fd62ce631c71fd0db3bff22d5c5de2c9b1ef99/src/backend/config/settings/base.py#L218-L223
Для файлов логов лучше использовать класс TimedRotatingFileHandler.

2024-03-24 06:06 UTC, ArtemKAF commented on src/backend/config/settings/base.py
> +        "console": {
https://github.com/Pet-projects-CodePET/Backend/blob/77fd62ce631c71fd0db3bff22d5c5de2c9b1ef99/src/backend/config/settings/base.py#L224-L228
Если и ограничивать уровень логгирования в консоль для контейнеров на серверах, то лучше сразу начиная с у ровня WARNING.

2024-03-24 06:06 UTC, ArtemKAF commented on src/backend/config/settings/base.py
> +        "mail_admins": {
https://github.com/Pet-projects-CodePET/Backend/blob/77fd62ce631c71fd0db3bff22d5c5de2c9b1ef99/src/backend/config/settings/base.py#L229-L234
Ограничение уровня логгирования здесь в ERROR не позволит отправлять в хэндлер сообщения логгирования уровня DEBUG из
https://github.com/Pet-projects-CodePET/Backend/blob/77fd62ce631c71fd0db3bff22d5c5de2c9b1ef99/src/backend/config/settings/base.py#L272-L277
И в чем смысл отправлять почтовые собщения с ошибками администраторам в файлы?

2024-03-24 06:06 UTC, ArtemKAF commented on src/backend/config/settings/base.py
В контейнерах на серверах нам абсолютно не нужны запросы sql к БД в консоли (только лишняя нагрузка), а для локальной разработки логгирования в файлы и отправка email сообщений администрации проекта абсолютно излишне.
Один из вариантов базовые настройки логгирования оставить в base.py, а в prod.py или local.py использовать метод update для словаря с настройками логгирования.
Другой только необходимые настройки для логгирования для каждого конкретного уровня разработки реализовывать в соответствующих файлах.

2024-03-24 06:06 UTC, ArtemKAF commented on src/backend/config/settings/base.py
> +LOGGING = {
https://github.com/Pet-projects-CodePET/Backend/blob/77fd62ce631c71fd0db3bff22d5c5de2c9b1ef99/src/backend/config/settings/base.py#L210-L215
Сомнительна необходимость реализации дополнительного упрощенного форматтера.

2024-03-24 07:20 UTC, Denis-Shtanskiy commented on src/backend/config/settings/base.py
> +LOGGING_MODULE = getenv("DJANGO_SETTINGS_MODULE", "config.settings.prod")
Это написал, чтобы была возможность прикрутить выбор, то есть дальше через ветвление в каждом файле выбирать нужное, можно разделить и хранить все это в отдельном файле.

2024-03-24 07:32 UTC, Denis-Shtanskiy commented on src/backend/config/settings/base.py
Для этого прикручен выбор переменной, как раз-таки, чтобы дальше уже все привести к виду где как и что работает, для начала нужно понимание что и как мы хотим логировать нужны ли некоторые логеры и тд.

2024-03-24 07:43 UTC, Denis-Shtanskiy commented on src/backend/config/settings/base.py
> +LOGGING = {
Я был в сомнениях по поводу него, вопрос для локальной разработки, вывод в консоль,  нужна полная информация или достаточно будет упрощенного

2024-03-24 07:46 UTC, Denis-Shtanskiy commented on src/backend/config/settings/base.py
> +        "mail_admins": {
Тут просто на момент написания оставил файловый бэк, чтобы было понимание нужна эта фича или нет, логика в том чтобы на почту отправлять. Суть в том что в логере стоит DEBUG, чтобы он смотрел на все сообщения начиная с DEBUG, а hendler уже обрабатывал и фильтровал передачу. Можно уровни сделать одинаковыми, вопрос в том что, будет ли когда-либо желание получать на почту что-то ниже чем ERROR, в этом была моя логика.

2024-04-02 20:05 UTC, Denis-Shtanskiy commented
Обновил свой код локально изменил по логированию все

2024-04-03 14:34 UTC, ArtemKAF reviewed
Интересный подход, но мне он не нравится из-за того, что в базовых настройках все кучей (менее удобно потом читать файл base), а потом в файлах "уточнения" настроек неизбежно дублирование кода, если понадобится какую-нибудь секцию удалять, к примеру, для dev и prod, а в local оставить.
И зачем-то метод setup_logging вызывается. Вроде бы и без него джанго прекрасно справляется с настройкой логгера исходя из того, что в словаре LOGGING прописано.

2024-04-03 14:35 UTC, ArtemKAF approved these changes

2024-04-03 18:00 UTC, merged