Feature/Add projects to favorite
Pet-projects-CodePET/Backend pull request #249
Opened 2024-05-03 17:56 UTC by Badmajor

Добавил action в ProjectViewSet. Так же поле is_favorite в модель Project, в фильтр ProjectFilter и серилизатор ReadProjectSerializer.

Ручки:
POST /projects/<project_id>/favorite/ - добавить проект в избранное.
DELETE /projects/<project_id>/favorite/ - удалить проект из избранного.

фильтр по избранным проектам:
/projects/?is_favorite=1

2024-05-04 08:27 UTC, Denis-Shtanskiy reviewed
Считаю надо подумать ещё, потестировать локально что написано, хотя бы на свагере

2024-05-04 08:27 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/views.py
> +            http_status = status.HTTP_204_NO_CONTENT
Лишняя строчка. И лучше тогда импортировать сразу статусы, из http без номеров, вроде лучшая практика считается.

2024-05-04 08:27 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/views.py
> +            http_status = status.HTTP_201_CREATED
Здесь как-будто весь метод стоит пересмотреть, есть ли смысл итак нагруженный бек нагружать дополнительными ветвлениями? И если метод выполнился, то нужен ли нам блок else, возможно лучше явно возвращать ответ? плюс нужен ли нам вообще тут бед реквест если action пускает только 2 метода, мне пока не понятно, может быть объяснишь

2024-05-04 08:27 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/serializers.py
> +        if user.is_authenticated:
Зачем проверка на аутентификацию, если во вью пропускает только аутентифицированных, то есть там уже работают мидлвари по токену, по идее, проверка излишняя. Ну и логика тогда не понятна , если юзер аутентифицирован, но нет избранных, тогда что, ну вернется false, а как понимать какие нужны нам проекты, как отображать будет фронт. Плюс тут выполняется доп. запрос к базе как будто, нужен ли он тут для проверки что у пользователя есть избранные или нет, нагрузка в разы возрастет на бэкенд, нужно возможно оптимизировать все этр, надо думать.

2024-05-04 08:27 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/filters.py
> +        if value and user.is_authenticated:
Какое значение любое? ну то есть, опять, мы сталкиваемся как и в сериализаторе, вот я сижу в апи авторизованный, но у меня нет никаких избранных и шлю вообще любую цифру и погнали) стоит ограничить юзеров как и фронтам жестко дать всего 2 цифры, для остального возвращать не отфильтрованный, ну и логика ломается, в услоивиях если у меня есть избранные, и я авторизован но не посылаю цифру, ну то есть фронт откуда узнает что нужно фильтровать для главной сразу, чтобы прислать нам значение, получается мы не увидим наши избранные. 
Мы на созвоне обсуждали это, Артем говорил что в фильтры не надо лезть итак нагружены они. Возможно нужен вообще свой вьюсет со своим покером=)

2024-05-04 10:00 UTC, Badmajor commented on src/backend/api/v1/projects/views.py
> +            http_status = status.HTTP_204_NO_CONTENT
Исправил, статусы импортируются из http

2024-05-04 10:01 UTC, Badmajor commented on src/backend/api/v1/projects/views.py
> +            http_status = status.HTTP_201_CREATED
оставил одно ветвление

2024-05-04 10:55 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +        if user.is_authenticated:
Permission во вьюхе пропускает всех.  Проверка нужна.

> class IsCreatorOrOwnerOrReadOnly(AllowAny):
    """
    Класс прав доступа чтение - любому пользователю, а редактирование только
    создателю или владельцу объекта.
    """
Сериализатор применяется для каждого проекта и to_representation возвращается по каждому проету, соответственно если в избранном то True, если нет, то False

оптимизировал запрос queryset'а во вьюхе:

`queryset = (
        Project.objects.all()
        .select_related(
            "creator",
            "owner",
        ).prefetch_related('is_favorite')
        .order_by("status", "-created")
    )`

2024-05-04 11:08 UTC, Badmajor commented on src/backend/api/v1/projects/filters.py
> +        if value and user.is_authenticated:
значение поправил, фильтрация сработает только при ?is_favorite=1, в остальных вернет без фильтрации.

Про отдельный вьюсет не соглашусь. 
Фильтры для этого и есть, что бы не плодить кучу однотипных вьюсетов. И их задача лишь отфильтровать кверисет.

2024-05-04 13:10 UTC, RavenIV commented on src/backend/apps/projects/models.py
> +    )
Мне кажется, не самое удачное название для поля модели, поскольку намекает на какое-то булево значение. Тут скорее что-то вроде favorited_by.

2024-05-04 13:10 UTC, RavenIV commented on src/backend/api/v1/projects/serializers.py
> +        return False
Проверка на аутентификацию тут по делу. 
Проверку на наличие проекта в избранном лучше сделать через метод exists(), который для таких случаев придуман: https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet.exists.
Сам итог функции можно оформить немного короче. Что-то типа такого:
return user.is_authenticated and <твой кверисет>.exists()

2024-05-04 17:07 UTC, ArtemKAF requested changes
https://github.com/Pet-projects-CodePET/Backend/blob/20376f024f36e45923bce72d85a6e9cee787d3f8/src/backend/api/v1/projects/filters.py#L65-L69
Что если необходимо будет при помощи этого фильтра отфильтровать проекты, которых нет в избранном?
В queryset до фильтраций не запрашивается из БД информация по избранным проектам. Текущая реализация, очень похоже, что вызовет по одному дополнительному запросу на каждый проект в queryset для фильтрации.
https://github.com/Pet-projects-CodePET/Backend/blob/20376f024f36e45923bce72d85a6e9cee787d3f8/src/backend/api/v1/projects/serializers.py#L111-L120
Здесь согласен с Ириной, что в текущей реализации не оптимально по каждому проекту выдергивать весь список избранного и в нем искать пользователя при помощи in.

Отсутствует контроль уникальности записей в избранном.
В уже существующем ПР-е можно было продолжить работу над этой задачей. Там уже почти все рализовано было, только проверить, оптимизировать и добавить то, чего не хватает.

2024-05-06 06:09 UTC, Badmajor commented on src/backend/apps/projects/models.py
> +    )
Исправил

2024-05-06 06:18 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +        return False
~~В сериализатор не передается кверисет, в него передается сам объект, если самим передавать кверисет, это ударит по производительности, потому что он будет передаваться для каждого объекта отдельно кверисет.~~

2024-05-06 07:03 UTC, Badmajor commented
> Что если необходимо будет при помощи этого фильтра отфильтровать проекты, которых нет в избранном?

Согласго требованиям фильтрация по "не в избранном не нужна", но проблем её добавить нет. Если нужно слелаю.

> В queryset до фильтраций не запрашивается из БД информация по избранным проектам. Текущая реализация, очень похоже, что вызовет по одному дополнительному запросу на каждый проект в queryset для фильтрации.

Насколько понял из флагмы, везде где есть отображение списка объектов есть и сердечко. так что я добавил в BaseProjectViewSet.queryset prefetch_related. 

> Здесь согласен с Ириной, что в текущей реализации не оптимально по каждому проекту выдергивать весь список избранного и в нем искать пользователя при помощи in.
Ответил Ирине.

> Отсутствует контроль уникальности записей в избранном.

Метод .add(obj) для manytomanyfield не создает дубликатов: https://docs.djangoproject.com/en/5.0/ref/models/relations/#related-objects-reference

> В уже существующем ПР-е можно было продолжить работу над этой задачей. Там уже почти все рализовано было, только проверить, оптимизировать и добавить то, чего не хватает.

Писал выше, что создание однотипных вьюсетов не оптимальное решение.

2024-05-06 07:21 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +        return False
Понял, о чём ты. Исправил. 

Документация рекомендует использовать именно такой подход, о октором ты говоришь.

2024-05-06 09:13 UTC, ArtemKAF approved these changes

2024-05-06 09:53 UTC, merged