[+] feature: add profiles preview, profile detail info ...
Pet-projects-CodePET/Backend pull request #252
Opened 2024-05-04 11:02 UTC by RavenIV

- Сделала сериализаторы для превью профилей специалистов и детальной информации профиля специалиста
- Создала вьюсет для профилей: доступны GET списка профилей специалистов, подробной инфо профиля специалиста. В дополнительный экшен перенесла чтение и редактирование профиля его владельцем.
- Перенесла валидацию количества создаваемых специалистов в сериализатор
- Сделала пагинацию для превью профилей специалистов

Обратите внимание на реализацию доступа к профилям специалистов в зависимости от настроек видимости. Сейчас получается так: например, если пользователь указал, что профиль не должен быть виден никому, то при попытке перейти на эндпоинт .../profiles/{id его профиля}/, статус ответа будет 404 Not Found (свой профиль при этом он все еще сможет увидеть по эндпоинту /profiles/me/)

2024-05-04 19:05 UTC, ArtemKAF requested changes
https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/paginations.py#L1-L10
В paginations.py для профилей и
https://github.com/Pet-projects-CodePET/Backend/blob/1c50ede2b66c876c49921ca11d605fdbf7f5a797/src/backend/api/v1/projects/paginations.py#L1-L17
В paginations.py для проектов. Все дублируется, кроме значения page_size. Есть смысл сразу вынести это дело в general.paginations и там организовать DefaultPagination, от которого уже наследовать класс пагинации для профилей и проктов и там, где необходимо переопределить параметр page_size.

https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/serializers.py#L168-L183
Тут не получится статическим методом? В методе нет обращений к объекту класса. Не хватает проектов, в которых пользователь владелец проекта, но не создатель его и не участник.

https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/serializers.py#L152-L166
Предудущий вариант казался несколько логичнее. Просто возвращать пустые значения полей контактов, если они скрыты настройками приватеости. Но это нужно будет обсудить на встрече вместе с фронтами и спросить как легче им будет обрабатывать.

https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/serializers.py#L89-L94
Использование метода format менее эффективно, чем реализовать константу с сообщением ошибки в constants.py при помощи f-строки. Встречал в статьях на просторах интернета и чат-гпт тоже объяснеет это тем, что f-строка один раз компилируется при определении, а метод format вызывается при каждом обращении.

https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/serializers.py#L186-L211
В этом сериализаторе можно попробовать применить следующее
```
    class Meta(ProfilePreviewReadSerializer.Meta):
        fields = (
            *(set(ProfilePreviewReadSerializer.Meta.fields) - {'specialists'}),
            дополнительные поля
        )
```
чтобы унаследовать поля меты ProfilePreviewReadSerializer без поля specialists и не дублировать все остальные. А все остальное унаследуется. Если mypy на такое не будет ругаться, как у меня в проектах, то это можно применить во всех сериализаторах и, например, вот тут:
https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/serializers.py#L241-L244
можно сделать вот так:
```python
    class Meta(ProfileMeReadSerializer.Meta):
        pass
```
Поле user_id сериализатор итак не даст поменять. Это излишне указывать его как read_only_fields, так как это поле с primary_key и сериализатор DRF по умолчанию его защищает для сохранения целостности данных в БД.

https://github.com/Pet-projects-CodePET/Backend/blob/538f3bab5e78815d536589607295c9ca65595c31/src/backend/api/v1/profile/serializers.py#L214-L222
Это тоже можно сразу в general.fields смело выносить и оттуда импортировать, так как рано или поздно еще где-нибудь это поле понадобится.

На счет вьюсетов и кверисетов нужно на созвоне обсудить.

2024-05-07 14:43 UTC, ArtemKAF commented on src/backend/api/v1/general/paginations.py
https://github.com/Pet-projects-CodePET/Backend/blob/9ee61741ee8580aa7d0e000cb8625ac1fa30708f/src/backend/api/v1/general/paginations.py#L6-L6
Лучше сразу в константы вынести.

2024-05-07 14:44 UTC, ArtemKAF commented on src/backend/api/v1/profile/paginations.py
https://github.com/Pet-projects-CodePET/Backend/blob/9ee61741ee8580aa7d0e000cb8625ac1fa30708f/src/backend/api/v1/profile/paginations.py#L5-L5
Еще одна константа.

2024-05-07 14:47 UTC, ArtemKAF commented on src/backend/api/v1/profile/serializers.py
https://github.com/Pet-projects-CodePET/Backend/blob/9ee61741ee8580aa7d0e000cb8625ac1fa30708f/src/backend/api/v1/profile/serializers.py#L124-L136
```python
fields: ClassVar[Tuple[str, ...]] = 
```
чтобы не использовать # type: ignore

2024-05-07 16:43 UTC, RavenIV commented on src/backend/api/v1/profile/serializers.py
попробовала. mypy все равно ругается, проверку не проходит

2024-05-07 17:02 UTC, ArtemKAF approved these changes

2024-05-08 09:23 UTC, merged