Fetaure/add mock data
Pet-projects-CodePET/Backend pull request #254
Opened 2024-05-09 10:33 UTC by Badmajor

Добавлена команда add_fake_users.
Флаги:
-s SAVE, --save SAVE :str. Save id, email, username and password to <path_to_file.csv>. Default None.
-a AMOUNT, --amount AMOUNT :int. Number of users. Default 1

Добавлена команда add_fake_profiles.
Флаги:
-a AMOUNT, --amount AMOUNT :int. Number of profiles. Default 1

Если юзеров или профессий не хватает для создания нужного количествао профилей, создает нужное количество.

Добавлена команда add_fake_projects.
Флаги:
-a AMOUNT, --amount AMOUNT :int. Number of profiles. Default 1

2024-05-10 11:13 UTC, RavenIV requested changes
Надо оптимизировать. 
Сейчас много циклов, лишних структур данных и запросов в бд. Если нужно создать десяток объектов, еще сработает, но если указать сотни, тысячи и т.д. (максимальное значение сейчас не установлено) в команде, то обработка займет слишком много времени.
Из того, что бросается в глаза: 
- где нужно получить количество объектов модели, использовать .count(), а не тянуть весь кверисет и потом к нему len() применять. 
- вместо долгой операции append() к списку, использовать list comprehension: [x for x in range(...)]

Еще надо подумать над логикой создания юзеров и профилей. Сейчас получается, что есть отдельная команда создания юзеров (по идее, кстати, при сохранении объекта в бд, должен по сигналу создаваться пустой профиль, не запускала твою команду, так что хз, сохраняется ли эта фича), плюс есть отдельная команда создания профилей, внутри которой ищутся или создаются юзеры без профилей. Может, стоит тогда оставить только команду генерации профилей, внутри которых генерить пользователей, как вариант

2024-05-10 11:13 UTC, RavenIV commented on src/backend/apps/general/management/commands/utils.py
> +    return user
Не поняла идею генерировать отдельно пароль и передавать его тут в аргументах, если ниже все равно применяется метод fake.password().

Не получится тут использовать bulk_create? В аргументы можно было бы передавать желаемое количество объектов. 
Если что, в нашей версии django (5) bulk_create возвращает созданные объекты списком https://docs.djangoproject.com/en/5.0/ref/models/querysets/#:~:text=argument%20was%20added.-,bulk_create,-()%C2%B6

2024-05-10 11:13 UTC, RavenIV commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +        if len(professions) != amount_professions:
здесь лучше применить метод <queryset>.count(), поскольку сам получаемый кверисет не используется

2024-05-10 11:13 UTC, RavenIV commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +            Profession.objects.bulk_create(new_professions)
вот это все проще и эффективнее будет написать через list comprehension
`new_professions = Profession.objects.bulk_create(
Profession(...) for _ in range(...)
)`

2024-05-10 11:13 UTC, RavenIV commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +        return self.fake.random_choices(professions, amount_professions)
Вообще большой вопрос нужно ли тут в принципе создавать фейковые профессии? Сейчас профессии можно предварительно через фикстуры загрузить

2024-05-12 08:47 UTC, Denis-Shtanskiy commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +        return self.fake.random_choices(professions, amount_professions)
Поддерживаю, не очень понимаю. У нас через фикстуры будут организованы профессии, при этом мы создаем доп нагрузку на БД в случае вызова этого метода, как-будто если хотим создать профессии - то просто создаем дополнительные, без проверки существования в БД.

2024-05-12 08:47 UTC, Denis-Shtanskiy commented on src/backend/apps/general/management/commands/add_fake_projects.py
> +        random_number = random.randint(1, 5)
Правильно ли я понимаю, что при каждой новой загрузке моковых данных, будет разное число направлений разработки, при этом мы и из базы будем возвращать это количество направлений? При этом ниже для юзера нет ограничения по количеству объектов. То есть у нас как будто условие даже не сработает, только если в базе изначально не меньше записей. Как по мне должна быть возможность выбора числа загружаемых направлений, юзеров и тд. Можно брать например из amount без рандома. И без проверки, как-будто, мы работаем с пустой базой и нужно сразу подгрузить данные чтобы тестировать код.

2024-05-12 08:47 UTC, Denis-Shtanskiy commented on src/backend/apps/general/management/commands/utils.py
> +    return user
Думаю просто упустил этот момент, но да нет смысла 2 раза создавать пароль

2024-05-13 06:46 UTC, Badmajor commented on src/backend/apps/general/management/commands/utils.py
> +    return user
Bulk_create не работет с create_user из-за хэширования паролей. 
Пароль передаётся из команды, fake_create_user, что бы сохранить в файле действиетльный пароль, в противном случае схранится хэш пароля, что вызовет сложность со входом, если он будет нужен.

2024-05-13 06:48 UTC, Badmajor commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +        if len(professions) != amount_professions:
Да, действительно, исправил

2024-05-13 07:23 UTC, Badmajor commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +            Profession.objects.bulk_create(new_professions)
Тут оба варианта применимы, вариант через list comprehenshion потребляет меньше оперативной памяти, но жертвуем читабельностью. Разница не значительная, особенно если учитывать, что команды не для постоянного пользования, а для разовых случаев. 

Тут просто нужно определить общий code style. Возможно вы уже что-то подобное приняли, тогда я подстроюсь)

2024-05-13 07:29 UTC, Badmajor commented on src/backend/apps/general/management/commands/add_fake_profiles.py
> +        return self.fake.random_choices(professions, amount_professions)
Логика в том, что бы досоздать профессии, в случае если они не подгружены. Если профессий достаточно, конструкция if не сработает.

Сделано на случай, если кому-то нужно просто подгрузить профили, не подгружая/создавая профессии и пользователей.

2024-05-13 08:03 UTC, Badmajor commented on src/backend/apps/general/management/commands/add_fake_projects.py
> +        random_number = random.randint(1, 5)
Не совсем, при создании проекта, будет добавляться к проекту рандомное количество рандомных направлений разработки. Если количества направлений не достаточно, создаст дополнительные. 

Для пользователей есть, 112 строка, обрезает перемешаный список ползователей. 

Если брать из amount, то при создании 1000 проектов, будет почти столько же направлений и пользователей созадаваться. 

Можно добавить флаги, не проблема, вопрос нужно ли это. 
Я считаю от 1 до 10 пользователей которые добавили в избранное или участвую в проекте достаточно, а shufle, что бы они не повторялись из проекта в проект. 

А на правления разработки из проекта в проетк повторяются, так что я посчитал, что шафл тут не нужен.

Если база пуста, он создаст нужное количество и пользователей и направлений.

2024-05-13 08:11 UTC, Badmajor commented
> Еще надо подумать над логикой создания юзеров и профилей. Сейчас получается, что есть отдельная команда создания юзеров (по идее, кстати, при сохранении объекта в бд, должен по сигналу создаваться пустой профиль, не запускала твою команду, так что хз, сохраняется ли эта фича), плюс есть отдельная команда создания профилей, внутри которой ищутся или создаются юзеры без профилей. Может, стоит тогда оставить только команду генерации профилей, внутри которых генерить пользователей, как вариант

Можно просто пользоваться созданем профилей, а создание пользователей, ко всему прочему имеет функционал сохранения данных пользователей для входа. это может пригодиться, например, для нагрузочного тестирования. 

а к созданию профиля, можно прикрутить функционал, который принудитьельно будет создавать пользователей, не проверяя, есть ли там пользователи. Если нужно сделаю через флаг, скажем, -f --force

2024-05-13 17:21 UTC, RavenIV commented on src/backend/apps/general/management/commands/utils.py
Еще думаю, может стоит добавить к названию файла нижнее подчеркивание, как в примере из доки (https://docs.djangoproject.com/en/5.0/howto/custom-management-commands/), как считаете? Так utils точно не будет доступен в качестве команды

2024-05-14 07:08 UTC, ArtemKAF approved these changes
Рабочий вариант, но во многих "мелочах" спорный.
К примеру часть констант используется из проекта для ограничений полей name или description, но при этом не используются константы используемые для bysyness
Вместо списков(особенно там, где используется append), лучше использовать другие сруктуры данных, которые специально разработаны для добавления элементов не за линейное время, а за константное.

2024-05-15 07:55 UTC, Badmajor commented
>     * где нужно получить количество объектов модели, использовать .count(), а не тянуть весь кверисет и потом к нему len() применять.

Изменил на count().  
>     * вместо долгой операции append() к списку, использовать list comprehension: [x for x in range(...)]

Изменил, теперь созание через лист компрехеншин

> Еще надо подумать над логикой создания юзеров и профилей. Сейчас получается, что есть отдельная команда создания юзеров (по идее, кстати, при сохранении объекта в бд, должен по сигналу создаваться пустой профиль, не запускала твою команду, так что хз, сохраняется ли эта фича), плюс есть отдельная команда создания профилей, внутри которой ищутся или создаются юзеры без профилей. Может, стоит тогда оставить только команду генерации профилей, внутри которых генерить пользователей, как вариант

Создания по сигналу нет, нужно добавить.
Оставил команду генерации пользователей, с проверкой на наличие профилия. Думаю, это предотвратит исключение в случае добавления сигнала.

2024-05-16 12:15 UTC, RavenIV approved these changes

2024-05-17 09:33 UTC, merged