refactor: Изменил фильтры и добавил поиск
Pet-projects-CodePET/Backend pull request #264
Opened 2024-05-12 20:55 UTC by Denis-Shtanskiy

- Исправил баги обнаруженные тестировщиками
- Провел рефакторинг фильтрации (сделал как у Иры)
- Добавил полнотекстовый поиск

2024-05-13 09:04 UTC, Badmajor reviewed
Вопрос к def project_search

2024-05-13 09:04 UTC, Badmajor commented on src/backend/api/v1/projects/filters.py
> +                search=search_query_ru | search_query_en
Нужно ли тут запрашивать два кверисета с реультатами, может лучше сначала опрелеить язык, например с помощью библиотеки langdetect, и вместо двух запросов делать один?

2024-05-13 09:18 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/filters.py
> +                search=search_query_ru | search_query_en
Посмотрю, не знал про библиотеку, спасибо) Думаю да, так вернее будет, через ветвление определить язык и тд

2024-05-14 05:52 UTC, ArtemKAF commented on src/backend/apps/projects/migrations/0007_project_search_vector_and_more.py
В develop было 8 файлов миграций. Теперь 9.

2024-05-14 06:21 UTC, ArtemKAF commented on src/backend/apps/projects/models.py
https://github.com/Pet-projects-CodePET/Backend/blob/d6756fb7b38b0849dd3b086d1e24cc467dd9fef1/src/backend/apps/projects/models.py#L163-L165
Действительно достаточно без указания полей, на основе которых будет строиться вектор?

2024-05-14 06:24 UTC, ArtemKAF commented on src/backend/api/v1/projects/filters.py
https://github.com/Pet-projects-CodePET/Backend/blob/d6756fb7b38b0849dd3b086d1e24cc467dd9fef1/src/backend/api/v1/projects/filters.py#L76-L85
```shell
File "/home/artemkaf/Dev/CodePET-Backend/src/backend/api/v1/projects/filters.py", line 82, in project_search
    return queryset.annotate(search=vector_ru | vector_en).filter(
                                    ~~~~~~~~~~^~~~~~~~~~~
  File "/home/artemkaf/.cache/pypoetry/virtualenvs/codepet-backend-UEAheHnO-py3.12/lib/python3.12/site-packages/django/db/models/expressions.py", line 124, in __or__
    raise NotImplementedError(
NotImplementedError: Use .bitand(), .bitor(), and .bitxor() for bitwise logical operations.
```
При попытке воспользоваться поиском следующим запросом:
```
GET http://localhost:9000/api/v1/projects/?search=test
```

2024-05-14 06:25 UTC, ArtemKAF approved these changes
Будет интересно посмотреть как это будет работать. Локально воспроизвести рабочий вариант не удалось.

2024-05-16 09:19 UTC, ArtemKAF requested changes
Нужно, либо доработать так, чтобы поле в модели с вектором поиска и индексом стали полезными, либо убрать их. На данный момент только лишние миграции от их добавления.

2024-05-16 09:19 UTC, ArtemKAF commented on src/backend/apps/projects/models.py
В данной реализации, что поле SearchVectorField, что индекс GinIndex добавлены бесполезно. Они никак не используются в процессе поиска.

2024-05-16 13:02 UTC, RavenIV reviewed
Согласна с Артемом, в этом варианте добавление SearchVectorField и GinIndex выглядит бессмысленно. Так понимаю, чтобы SearchVectorField работал, его нужно в каком-то месте заполнить триггерами, как в доке [написано](https://docs.djangoproject.com/en/5.0/ref/contrib/postgres/search/#:~:text=text%20search.-,SearchVectorField,-%C2%B6). 
Вообще тема поиска очень интересная, будет здорово послушать, что успели накопать)

2024-05-17 14:45 UTC, Denis-Shtanskiy commented on src/backend/apps/projects/models.py
Убрал поля

2024-05-17 16:59 UTC, ArtemKAF approved these changes

2024-05-18 20:22 UTC, merged