251 feature invite to project
Pet-projects-CodePET/Backend pull request #291
Opened 2024-05-31 09:23 UTC by Badmajor

Для создания, удаления и просмотра приглашений `projects/invitations`
Данные валидируются. Проверяется, что проекту действительно требуется этот специалист, что пользователь не участвует в проекте, так же что у приглашенного есть подходящая специальность.

При принятии приглашения, изменении статуса на ACCEPTED, пользователь добавляется в проект. 

При создании приглашения пользователю отправляется письмо, что его приглашают в проект

2024-06-02 09:25 UTC, Denis-Shtanskiy reviewed
Есть вопросы, есть предложения, в остальном хорошая работа

2024-06-02 09:25 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/serializers.py
> +            *BaseParticipationRequestSerializer.Meta.fields,
Не очень понял логику наследования, если мы наследуемся от ReadParticipation...., В мета передаем его же, но поля извлекаем из Base? Зачем нам тогда тут прокладка в виде Read, плюс там вычисляемые поля. доп нагрузка. Или это было сделано для статуса? если да, то его не будет как и поля is_viewed

2024-06-02 09:25 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/serializers.py
> +            *BaseParticipationRequestSerializer.Meta.fields,
Похоже та же история что и выше

2024-06-02 09:25 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/serializers.py
> +                project.participants.all().values_list("id", flat=True),
Зачем нам усложнять запрос сначала все поля получить а потом только список айди? можно же сразу получить ID, при этом, в случае участников, мы получим id для промежуточной таблицы, то есть не id user.

2024-06-02 09:25 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/serializers.py
> +        status = validated_data.get("status", None)
Будет ли у нас тут None? default = IN.Progress верно же? значит мы можем передать либо отказ либо принятие либо ничего=дефолт. Плюс это поле выбора, вроде никак тут None не получим

2024-06-02 09:25 UTC, Denis-Shtanskiy commented on src/backend/api/v1/projects/views.py
> +            .prefetch_related(
По твоему вопросу на оптимизацию запросов, можно использовать Prefetch(field, qs=Model.object.select_related()).
По поводу only - насколько мне известно only сразу делает запрос(обязательно вызывает поля указанные) и если есть select_related и это поле не указано в only то это ошибка, возможно и с prefetch та-же история. То есть явно должны быть все поля указаны иначе не сработает доп запрос в одном

2024-06-03 06:10 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +            *BaseParticipationRequestSerializer.Meta.fields,
Моя невнимательность, тут хотел добавить поле author к ReadParticipation

Поправил

2024-06-03 08:56 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +                project.participants.all().values_list("id", flat=True),
поменял вообще логику проверки. Забыл про рекомендации Ирины

2024-06-03 09:24 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +        status = validated_data.get("status", None)
Не понял.

Это просто безопасное извлечение status из validated_data

2024-06-03 09:48 UTC, Badmajor commented
Переделал логику валидации данных.

2024-06-03 11:26 UTC, Badmajor commented on src/backend/api/v1/projects/views.py
> +            .prefetch_related(
с запросами разобрался

2024-06-04 09:01 UTC, Denis-Shtanskiy approved these changes
Выглядит хорошо

2024-06-04 15:55 UTC, ArtemKAF requested changes
При текущей реализации никак не контролируется кто какие поля может добавлять/редактировать. Автор приглашения может спокойно писать "answer", а тот, кого приглашают может без проблем редактировать "cover_letter"

2024-06-04 15:55 UTC, ArtemKAF commented on src/backend/apps/projects/signals.py
https://github.com/Pet-projects-CodePET/Backend/blob/2e52fb893fef7036ef4f5845939bb6156dec06d2/src/backend/apps/projects/signals.py#L21-L26
Это нужно реализовать с помощью Celery задачи, чтобы не "ловить" проблемы в случае, если будет не доступна отправка email.
И предусмотреть более универсально, без хардкода email-адреса проекта, да и шаблон с письмом лучше реализовать в соответствующей директории, чем хардкодить текст письма.

2024-06-04 15:55 UTC, ArtemKAF commented on src/backend/api/v1/projects/serializers.py
https://github.com/Pet-projects-CodePET/Backend/blob/2e52fb893fef7036ef4f5845939bb6156dec06d2/src/backend/api/v1/projects/serializers.py#L480-L510
Нужно будет "допиливать". Сериализатор используется как при POST запросе, так и при PATCH запросе, а метод валидации ориентируется только на POST запрос.
if user: в текущей реализации излишняя проверка, так как поле user обязательное и сериализатор мало того, что недопустит пустого значения в поле user, так еще и сам провалидирует, что в поле user обязательно существующий в БД пользователь.
Круто, что реализована проверка соответствия профессии у пользователя професии, на которую пользователь приглашается.

2024-06-04 15:55 UTC, ArtemKAF commented on src/backend/apps/projects/models.py
https://github.com/Pet-projects-CodePET/Backend/blob/2e52fb893fef7036ef4f5845939bb6156dec06d2/src/backend/apps/projects/models.py#L291
Префикс "my_" лишний и у автора может быть много пригляшений, поэтому наиболее корректный related_name будет выглядеть invitations_to_projects.
https://github.com/Pet-projects-CodePET/Backend/blob/2e52fb893fef7036ef4f5845939bb6156dec06d2/src/backend/apps/projects/models.py#L295-L296
Тот, кого приглашают, участником проекта станет только в том случае, если примет приглашение, а может и не принять. До тех пор, пока приглашаемый не принял приглашение, он не является участником. Поэтому корректно назвать "приглашение для участия".

2024-06-04 15:55 UTC, ArtemKAF commented on src/backend/api/v1/projects/views.py
https://github.com/Pet-projects-CodePET/Backend/blob/2e52fb893fef7036ef4f5845939bb6156dec06d2/src/backend/api/v1/projects/views.py#L331-L360
Нужно будет "допиливать". К примеру, для отображения списка приглашений не нужны все поля.

2024-06-05 10:43 UTC, Badmajor commented on src/backend/apps/projects/models.py
> Префикс "my_" лишний и у автора может быть много пригляшений, поэтому наиболее корректный related_name будет выглядеть invitations_to_projects.

invitations_to_projects это related_name для user ( тот кого пригласили), а для  author использую с my_ там же тольк от приглашения которые он создал.

verbose_name поправил

2024-06-05 10:47 UTC, Badmajor commented on src/backend/api/v1/projects/views.py
не совсем понял, какие поля не нужны для отображения списка? 
ты про "project__creator",  "project__owner"?

2024-06-05 12:25 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
Разделил сериализаторы на POST и APTCH запросы. 

Что касается счетчика думаю его проще реализовать в самой модели, что бы не дергать его из разых сериализаторов и вьюх. Короче автоматизировать.

2024-06-09 09:56 UTC, Badmajor commented on src/backend/apps/projects/signals.py
Готово

2024-06-15 06:36 UTC, ArtemKAF approved these changes
Уже гораздо лучше.
Но всетаки, похоже, что нужно созваниваться, чтобы объяснить, что даже в данной реализации нет контроля кто какие поля может изменять при работе с приглашением в проект и другие "мелочи".
Круто, что нашел решение с некоректным отображением тела запроса в сваггере.

2024-06-26 17:18 UTC, Badmajor commented
ансвер меняет только приглошенный

письмо не меняется

2024-07-10 21:19 UTC, Badmajor commented
Поправил работу приглашений под изменеиня в модели project. Так же подправил схему декораторами

2024-07-10 21:24 UTC, merged