fix: Внес изменения:
Pet-projects-CodePET/Backend pull request #361
Opened 2024-08-01 19:46 UTC by Denis-Shtanskiy

- Добавил там где по задумке должно быть поле владельца проекта, точнее указание что поле для чтения
- Сделал требуемую валидацию по безопасности полей для редактора от фронтов (about and description)
- Добавил так же для сопроводительного письма валидацию в приглашениях
- Написал комментарий для сериализатора, в откликах, не очень понимаю зачем и как это работает, нужно разбираться
- У меня не запускались тесты при пре-коммите, изменил немного и ещё у тебя видимо где-то опечатка или я хз=)

2024-08-01 19:48 UTC, Denis-Shtanskiy commented
По поводу овнера написал в телеграме, по-поводу других полей посмотри, потестируй, если есть возможность, я так и не исправил свою проблему с путями и тд.

2024-08-02 08:01 UTC, Badmajor requested changes

2024-08-02 08:01 UTC, Badmajor commented on pyproject.toml
> +pythonpath = "src/backend"
я я голову ломал, всё оказалось просто!!!

2024-08-02 08:01 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +            "answer",  # какая-то дичь происходит, зачем нам тут видеть и ответ
Потому что это метод просмотр конкретного запроса

2024-08-02 08:01 UTC, Badmajor commented on src/backend/api/v1/projects/serializers.py
> +    def to_representation(self, instance):
Не нужно переопределять, 
Наследуется от ReadRetrieveParticipationRequestSerializer
он там уже определен

2024-08-02 08:02 UTC, Badmajor commented
Норм, но есть лишнее переопределение

2024-08-02 09:34 UTC, Badmajor commented
Добавил тест поля Owner для сериализатора проектов. 

поправил извлечение user из request для метода get_is_favorite в ReadProjectSerializer. Извлекается более безопасно.

2024-08-02 09:35 UTC, Badmajor commented
И удалил этот метод _get_base_field

2024-08-02 10:08 UTC, Badmajor approved these changes

2024-08-02 10:08 UTC, merged